name: PhotoboothProject
title: Photobooth Project
description: OpenSource Photobooth web interface for Linux and Windows.
repository: PhotoboothProject/PhotoboothProject.github.io
url: http://PhotoboothProject.github.io
baseurl: ""

plugins:
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true

include:
  - index.md
  - Changelog.md
  - changelog.md
  - CHANGELOG.md
  - FAQ.md
  - FAQ_MENU.md
  - Installation-on-Debian.md
  - Installation-on-Windows.md
  - Update-Photobooth.md
  - INSTALL.md
  - Install.md
  - install.md

theme: jekyll-theme-primer
