name: PhotoboothProject
description: OpenSource Photobooth web interface for Linux and Windows.
repository: PhotoboothProject/PhotoboothProject.github.io
url: http://PhotoboothProject.github.io
baseurl: ""

plugins:
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true

include:
  - Index.md
  - Changelog.md
  - FAQ.md
  - Installation-on-Debian.md
  - Installation-on-Windows.md
  - Update-Photobooth.md

theme: jekyll-theme-tactile
